In [2]:
pip install numpy


     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ------------- -------------------------- 20.5/61.0 kB ? eta -:--:--
     -------------------------------------- 61.0/61.0 kB 819.4 kB/s eta 0:00:00
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.1/15.5 MB 825.8 kB/s eta 0:00:19
   ---------------------------------------- 0.1/15.5 MB 825.8 kB/s eta 0:00:19
   ---------------------------------------- 0.1/15.5 MB 825.8 kB/s eta 0:00:19
   ---------------------------------------- 0.1/15.5 MB 825.8 kB/s eta 0:00:19
   ---------------------------------------- 0.1/15.5 MB 327.3 kB/s eta 0:00:48
   ---------------------------------------- 0.1/15.5 MB 327.3 kB/s eta 0:00:48
   ---------------------------------------- 0.1/15.5 MB 327.3 kB/s eta 0:00:48
   ---------------------------------------- 0.1/15.5 MB 327.3 kB/s eta 0:00:48
  

In [3]:
import numpy as np

In [11]:
random_int_array = np.random.randint(1, 50, size=(10))
random_int_array

array([ 1, 44, 37, 41, 15, 13,  5, 14, 32, 21])

In [12]:
np.mean(random_int_array)

22.3

In [13]:
random_int_array1 = np.random.randint(1, 10, size=(3, 3))
random_int_array1

array([[9, 5, 5],
       [2, 8, 1],
       [6, 6, 2]])

In [14]:
random_int_array2 = np.random.randint(1, 10, size=(3, 3))
random_int_array2

array([[5, 8, 4],
       [5, 8, 9],
       [3, 4, 1]])

In [15]:
array = np.add(random_int_array1, random_int_array2)

In [16]:
array

array([[14, 13,  9],
       [ 7, 16, 10],
       [ 9, 10,  3]])

In [17]:
np.mean(array)

10.11111111111111

In [22]:
random_int_array = np.random.randint(1, 100, size=(20))
random_int_array

array([82,  3, 30, 88, 58, 90,  4, 93, 10, 65, 69, 56, 57, 89, 44, 30, 72,
        9, 77, 90])

In [23]:
condition=random_int_array>50
new_array=random_int_array[condition]
new_array

array([82, 88, 58, 90, 93, 65, 69, 56, 57, 89, 72, 77, 90])

In [4]:
random_int_array = np.random.randint(1, 10, size=(10))
random_int_array

array([1, 6, 4, 7, 6, 7, 3, 6, 5, 7])

In [7]:
np.random.shuffle(random_int_array)
random_int_array

array([6, 7, 7, 6, 6, 1, 5, 7, 3, 4])

In [8]:
np.random.choice(random_int_array)

7

In [9]:
np.random.choice(random_int_array)

3